

# This file was *autogenerated* from the file test_dobble.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7)
from dobble import *

N = _sage_const_2 

for _ in range(_sage_const_1 ,N):
   # rnd = randint(1, N)
   # rnd_prime = next_prime(rnd)
    rnd_prime = _sage_const_7 
    print("rnd_prime ", rnd_prime)
    mazo = genera_mazo(rnd_prime + _sage_const_1 )
    dobble = IncidenceStructure(len(mazo), mazo)

    plano_proy = designs.projective_plane(rnd_prime)

    print(plano_proy.is_isomorphic(dobble))

